version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  infinisoft-web-v2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - run:
          name: dependencies
          command: yarn install
      - run:
          name: build
          command: yarn run build

workflows:
  frontend:
    jobs:
      - infinisoft-web-v2




          