version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  infinisoft-web-v2:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
          install-yarn: true 
          node-version: '16.3.0' 
          yarn-version: '1.22.17' 
      - checkout
      - run: git fetch --all
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}
            - yarn-packages-v1
      - run: yarn install
      - run: git config --global user.email $GITHUB_EMAIL
      - run: git config --global user.name $GITHUB_USER
      - run: yarn ci:bootstrap
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn ci:version
      - run: git tag
      - run: echo 'export TAG=`git describe --abbrev=0 --tags $(git rev-list --tags --max-count=2) | sed -n 2p`' >> $BASH_ENV
      - run: echo $TAG
      - run: yarn ci:build
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID 
          aws-region: AWS_REGION 
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY 
          from: packages/web/build 
          to: s3://infini-soft.com/

workflows:
  frontend:
    jobs:
      - infinisoft-web-v2
