version: 2.1

orbs:
  node: circleci/node@5.0.2

parameters:
  run-frontend:
    type: boolean
    default: true

jobs:
  infinisoft-web-v2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - node/install-packages:
          with-cache: false 
          override-ci-command: install
      - run: build

workflows:
  frontend:
    when: << pipeline.parameters.run-frontend >>
    jobs:
      - infinisoft-web-v2
